/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutoriaRouteImport } from './routes/tutoria'
import { Route as MeusCursosRouteImport } from './routes/meus-cursos'
import { Route as GameficacaoRouteImport } from './routes/gameficacao'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvaCursoSlugAulaLessonIdRouteImport } from './routes/ava.curso.$slug.aula.$lessonId'

const TutoriaRoute = TutoriaRouteImport.update({
  id: '/tutoria',
  path: '/tutoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCursosRoute = MeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const GameficacaoRoute = GameficacaoRouteImport.update({
  id: '/gameficacao',
  path: '/gameficacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaCursoSlugAulaLessonIdRoute =
  AvaCursoSlugAulaLessonIdRouteImport.update({
    id: '/ava/curso/$slug/aula/$lessonId',
    path: '/ava/curso/$slug/aula/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/gameficacao': typeof GameficacaoRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/tutoria': typeof TutoriaRoute
  '/ava/curso/$slug/aula/$lessonId': typeof AvaCursoSlugAulaLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/gameficacao': typeof GameficacaoRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/tutoria': typeof TutoriaRoute
  '/ava/curso/$slug/aula/$lessonId': typeof AvaCursoSlugAulaLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificados': typeof CertificadosRoute
  '/gameficacao': typeof GameficacaoRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/tutoria': typeof TutoriaRoute
  '/ava/curso/$slug/aula/$lessonId': typeof AvaCursoSlugAulaLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificados'
    | '/gameficacao'
    | '/meus-cursos'
    | '/tutoria'
    | '/ava/curso/$slug/aula/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificados'
    | '/gameficacao'
    | '/meus-cursos'
    | '/tutoria'
    | '/ava/curso/$slug/aula/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/certificados'
    | '/gameficacao'
    | '/meus-cursos'
    | '/tutoria'
    | '/ava/curso/$slug/aula/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadosRoute: typeof CertificadosRoute
  GameficacaoRoute: typeof GameficacaoRoute
  MeusCursosRoute: typeof MeusCursosRoute
  TutoriaRoute: typeof TutoriaRoute
  AvaCursoSlugAulaLessonIdRoute: typeof AvaCursoSlugAulaLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutoria': {
      id: '/tutoria'
      path: '/tutoria'
      fullPath: '/tutoria'
      preLoaderRoute: typeof TutoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-cursos': {
      id: '/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof MeusCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameficacao': {
      id: '/gameficacao'
      path: '/gameficacao'
      fullPath: '/gameficacao'
      preLoaderRoute: typeof GameficacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ava/curso/$slug/aula/$lessonId': {
      id: '/ava/curso/$slug/aula/$lessonId'
      path: '/ava/curso/$slug/aula/$lessonId'
      fullPath: '/ava/curso/$slug/aula/$lessonId'
      preLoaderRoute: typeof AvaCursoSlugAulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadosRoute: CertificadosRoute,
  GameficacaoRoute: GameficacaoRoute,
  MeusCursosRoute: MeusCursosRoute,
  TutoriaRoute: TutoriaRoute,
  AvaCursoSlugAulaLessonIdRoute: AvaCursoSlugAulaLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
